import React, {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar/Navbar';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';


import NavbarTop from "../components/Navbar/NavbarTop";
import SmallBottomBar from "../components/SmallBottomBar";
import LRButtons from "../components/LRButtons";
import NameNdDetails from "../components/NameNdDetails";
import MenuButton from "../components/MenuButton";
import MenuContent from "../components/MenuContent";






const images = [

  {
    id:1,
    type:'car',
    name:'Model 3',
    detail:"Order Online for Touchless Delivery",
    buttonL:'CUSTOM ORDER',
    buttonR:'EXISTING INVENTORY',
    imgPath:`https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2072&q=80`,
  
  },
  {
    id:2,
    type:'car',
    name:'Model Y',
    detail:"Order Online for Touchless Delivery",
    buttonL:'CUSTOM ORDER',
    buttonR: 'EXISTING INVENTORY',
    imgPath: `https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80`,
  
  },
  {
    id:3,
    type:'car',
    name:'Model X',
    detail:"Order Online for Touchless Delivery",
    buttonL:'CUSTOM ORDER',
    buttonR:'EXISTING INVENTORY',
    imgPath: `https://images.unsplash.com/photo-1558992658-08a063bb01af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80`,
    
  },  
  {
    id:4,
    type:'car',
    name:'Model S',
    detail:"Order Online for Touchless Delivery",
    buttonL:'CUSTOM ORDER',
    buttonR:'EXISTING INVENTORY',
    imgPath:`https://images.unsplash.com/photo-1633507104426-f2be1293f5a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1906&q=80`,
  },
  {
    id:5,
    type:'solar',
    name:'Solar Panels',
    detail:"Lowest Cost Solar Panels in America",
    buttonL:'ORDER NOW',
    buttonR:'LEARN MORE',
    imgPath:`https://images.unsplash.com/flagged/photo-1566838616631-f2618f74a6a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80`,
    footer:''
  },
  {
    id:6,
    type:'solar',
    name:'Solar Roof',
    detail:'Produce Clean Energy From Your Roof',
    buttonL:'ORDER NOW',
    buttonR:'LEARN MORE',
    imgPath:`https://images.unsplash.com/photo-1637417494521-78b4d1d33029?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80`,
    
  },
  {
    id:7,
    type:'accessories',
    name:'Accessories',
    detail:'',
    buttonL:'SHOP NOW',
    buttonR:'',
    imgPath:`https://images.unsplash.com/photo-1593941707882-a5bba14938c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80`,
    

  }
 
]




function FadeInSection(props){

  const [isVisible,setVisible] = React.useState(false);
  const domRef = React.useRef();
  React.useEffect(()=>{
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => setVisible(entry.isIntersecting));
    });
    observer.observe(domRef.current);
  }, []);
  return (
    <div
      className={`fade-in-section ${isVisible ? "is-hidden": ""}`}
      ref={domRef}
    >
      {props.children}
    </div>
  );
}




export default function Home() {

  const [isShow,setIsShow] = useState(false);


  const handleToggle = () => {

     setIsShow(!isShow);
  }


  return (
  <>
    <Head>
        <title>Mesla Auto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="https://iconarchive.com/download/i54293/crountch/one-piece-jolly-roger/Luffys-flag.ico" />
    </Head>
   
  
    
     <NavbarTop/>
      <div className="fixed top-13 z-20"><Navbar/></div>
    
   
    
    
    
     <MenuButton
        handleToggle={handleToggle}
     />
   
    {isShow ?
           (
       <MenuContent
          handleToggle={handleToggle}
       />        
    ) : (<div></div>)}

    <section className={isShow ? `overflow-y-hidden fixed h-[100%] w-[100%]` 
    : ``}>
    
    <div className="w-[100%]">      
      {images.map(({id,name,detail,imgPath,buttonL,buttonR,type})=>(
    
    <div key={id} className="snap-center relative
     z-10 h-screen w-[100%]">
        
            <Image
                src={imgPath}
                layout="fill"
                className={id===1 ? "rounded-t-lg object-cover" : 
                "object-cover w-[100%]"}
                alt=""
            />   
           
            
    <FadeInSection className=""> 
        
    
        <NameNdDetails
           type={type}
           id={id}
           name={name}
           detail={detail}
        />                                
                        
        <LRButtons
           buttonL={buttonL}
           buttonR={buttonR}
           id={id}
        />
    <div className={id === 1 ? `
          cursor-pointer fixed mt-[3rem] flex w-[100%] top-[80%] justify-center 
           lg:top-[74%]` : "hidden"}>    
          <KeyboardArrowDownIcon
            className="mt-[5%] text-4xl text-cyan-500 scale-[2] shadow-xl shadow-black
             hover:text-green-200 hover:shadow-red-500"
          />       
    </div> 

       <SmallBottomBar
         id={id}
       />
                
      
    </FadeInSection> 
         
    </div> 
          
    ))}
    </div>
    </section>
  
    
  </>
    
  );
}


